# Documentation:
# https://docs.netlify.com/configure-builds/file-based-configuration

[build]
  publish = "dist"
  command = "cd .. && npm i && npm run build && cd client"

[functions]
  directory = "../api/_deploy/netlify"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 301
  force = true

[dev]
  port = 8080
  autoLaunch = true